<template>
  <div class="card">
    <div class="card-header" @click="link(classItem.id)">
      {{ classItem.name }}
    </div>
    <div class="card-body">
      <el-tag type="success">所属课程：{{ classItem.courseName }}</el-tag>
    </div>
    <div class="card-footer">
      <el-tag type="primary">开课时间：{{ dateRegExp(classItem.createTime) }}</el-tag>
    </div>
  </div>
</template>

<script>
export default {
  name: "ClassCard",
  props: {
    classItem: Object,
  },
  methods: {
    link(classId) {
      this.$router.push({
        path: "/classInfo",
        query: {
          classId: classId,
        },
      });
    },
    dateRegExp(date) {
      const regexp = /(\d{4})-(\d{2})-(\d{2})\s(\d{2}):(\d{2}):(\d{2})/;
      return date.replace(regexp, "$1 年 $2 月 $3 日");
    },
  },
};
</script>

<style scoped>
.card {
  border: 1px solid var(--green-secondary-color);
  display: flex;
  flex-direction: column;
  width: 240px;
  height: 200px;
  background-color: white;
}

.card:hover {
  border: 1px solid var(--orange-color);
  box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 1px 5px 0 rgba(0, 0, 0, 0.12), 0 3px 1px -2px rgba(0, 0, 0, 0.2); /* generated by ChatGPT :p */
}

.card-header {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 1rem;
  flex-grow: 1;
  background-color: var(--green-secondary-color);
  color: #fff;
  text-align: center;
  font-size: 20px;
  font-weight: bold;
  line-height: 1.5em;
}

.card:hover .card-header {
  background-color: var(--orange-color);
}

.card-header:hover {
  cursor: pointer;
}

::-webkit-scrollbar {
  display: none;
}

.card-body {
  padding: 0.5rem;
  border-bottom: 1px solid var(--green-secondary-color);
}

.card:hover .card-body {
  border-bottom: 1px solid var(--orange-color);
}

.card-footer {
  padding: 0.5rem;
}
/* 
.card:hover .card-footer {
  background-color: var(--orange-color);
} */
</style>
