<template>
  <div class="card">
    <div class="card-header" @click="link(classItem.id)">
      {{ classItem.name }}
    </div>
    <!-- <div class="card-footer"">进入班级</div> -->
  </div>
</template>

<script>
export default {
  name: "ClassCard",
  props: {
    classItem: Object,
  },
  methods: {
    link(classId) {
      this.$router.push({
        path: "/classInfo",
        query: {
          classId: classId,
        },
      });
    },
  },
};
</script>

<style scoped>
.card {
  border: 1px solid var(--green-color);
  display: inline-flex;
  flex-direction: column;
  width: 240px;
  height: 160px;
  background-color: white;
}

.card:hover {
  border: 1px solid var(--orange-color);
  box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 1px 5px 0 rgba(0, 0, 0, 0.12), 0 3px 1px -2px rgba(0, 0, 0, 0.2); /* generated by ChatGPT :p */
}

.card-header {
  display: flex;
  justify-content: space-between;
  flex-grow: 1;
  align-items: center;
  padding: 1rem;
  background-color: var(--green-color);
  color: #fff;
  text-align: left;
  font-size: 24px;
  font-weight: bold;
  line-height: 1.5em;
}

.card-header:hover {
  cursor: pointer;
  background-color: var(--orange-secondary-color);
}

::-webkit-scrollbar {
  display: none;
}

.card-body {
  float: left;
  padding: 1rem;
  flex-grow: 1;
  text-align: left;
  border-bottom: 1px solid var(--green-color);
}

.card-footer {
  padding: 1rem;
  font-size: 14px;
  color: var(--green-color);
}

.card-footer:hover {
  cursor: pointer;
  color: var(--orange-secondary-color);
}
</style>
