<template>
  <div class="card">
    <div class="card-header">
      {{ course.name }}
    </div>
    <div class="card-body">
      {{ course.info }}
    </div>
    <el-popover placement="bottom" width="200" trigger="hover">
      <div class="card-footer" type="text" slot="reference">查看班级</div>
      <div
        v-show="course.classList.length != 0"
        class="course-item"
        v-for="(item, index) in course.classList"
        :key="index"
        @click="linkToClass(item.id)"
      >
        {{ item.name }}
      </div>
      <div v-show="course.classList.length == 0"><bold>空</bold></div>
    </el-popover>
  </div>
</template>

<script>
export default {
  name: "CourseCard",
  props: {
    course: Object,
  },
  data() {
    return {
      showDropdown: false,
    };
  },
  methods: {
    linkToClass(courseId) {
      this.$router.push({
        path: "/courseInfo",
        query: {
          courseId: courseId,
        },
      });
    },

    linkToClass(classId) {
      this.$router.push({
        path: "/classInfo",
        query: {
          classId: classId,
        },
      });
    },

    notEmpty(list) {
      return list.length > 0;
    },
  },
};
</script>

<style scoped>
.card {
  border: 1px solid var(--green-color);
  display: inline-flex;
  flex-direction: column;
  width: 240px;
  height: 240px;
  background-color: white;
}

.card:hover {
  border-radius: 2px;
  box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 1px 5px 0 rgba(0, 0, 0, 0.12), 0 3px 1px -2px rgba(0, 0, 0, 0.2); /* generated by ChatGPT :p */
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem;
  background-color: var(--green-color);
  color: #fff;
  text-align: left;
  font-size: 18px;
  font-weight: bold;
  white-space: nowrap;
  overflow: auto;
  text-overflow: ellipsis;
}

.card-body {
  float: left;
  padding: 1rem;
  flex-grow: 1;
  text-align: left;
  border-bottom: 1px solid var(--green-color);
}

.card-footer {
  padding: 1rem;
  font-size: 14px;
}

.card-footer:hover {
  color: var(--green-color);
}

.course-item:hover {
  cursor: pointer;
  color: var(--green-color);
}
</style>
